<?php

namespace common\models\ar;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "inspecting_mkl_bj_items".
 *
 * @property int $id
 * @property int $inspecting_id
 * @property int $grade 1=Grade A, 2=Grade B, 3=Grade C, 4=Piece Kecil, 5=Sample
 * @property string|null $join_piece
 * @property float $qty
 * @property string|null $note
 *
 * @property InspectingMklBj $inspecting
 *
 * @property string $gradeName
 */
class InspectingMklBjItems extends \yii\db\ActiveRecord
{
    const GRADE_A = 1; const GRADE_B = 2; const GRADE_C = 3; const GRADE_PK = 4; const GRADE_SAMPLE = 5;
    /**
     * @return array
     */
    public static function gradeOptions(){
        return [self::GRADE_A => 'Grade A', self::GRADE_B => 'Grade B', self::GRADE_C => 'Grade C', self::GRADE_PK => 'Piece Kecil', self::GRADE_SAMPLE => 'Sample'];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'inspecting_mkl_bj_items';
    }

    /**
     * {@inheritdoc}
     */
    public function fields()
    {
        $fields = parent::fields();
        $newFields = [
            'gradeLabel' => function($model){
                return $model->gradeName;
            }
        ];
        return ArrayHelper::merge($fields, $newFields); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['inspecting_id', 'grade', 'qty'], 'required'],
            [['inspecting_id', 'grade', 'join_piece'], 'default', 'value' => null],
            ['join_piece', 'match', 'pattern' => '/^[A-Z]{1,2}$/'],
            [['inspecting_id'], 'integer'],
            ['grade', 'in', 'range' => [InspectingItem::GRADE_A, InspectingItem::GRADE_B, InspectingItem::GRADE_C, InspectingItem::GRADE_PK, InspectingItem::GRADE_SAMPLE]],
            [['qty'], 'number'],
            [['note'], 'string'],
            [['join_piece'], 'string', 'max' => 10],
            [['inspecting_id'], 'exist', 'skipOnError' => true, 'targetClass' => InspectingMklBj::className(), 'targetAttribute' => ['inspecting_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'inspecting_id' => 'Inspecting ID',
            'grade' => 'Grade',
            'join_piece' => 'Join Piece',
            'qty' => 'Qty',
            'note' => 'Note',
            'gradeName' => 'Grade',
        ];
    }

    /**
     * @inheritDoc
     */
    public function attributeHints()
    {
        return [
            'join_piece' => 'Contoh: A',
        ];
    }

    /**
     * Gets query for [[Inspecting]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getInspecting()
    {
        return $this->hasOne(InspectingMklBj::className(), ['id' => 'inspecting_id']);
    }

    /**
     * @return string
     */
    public function getGradeName()
    {
        return self::gradeOptions()[$this->grade];
    }
}
